### ISSUE TITLE
More specific Errors thrown would be better in some cases

### ISSUE THREAD

**Issue by Ladas** [excon/excon#513]
Would be nice if we could have https://github.com/excon/excon/blob/master/lib/excon/errors.rb#L13
defined a subclasses of Excon::Errors::SocketError

so e.g. Excon::Errors::SocketError::BadCertificate, Excon::Errors::SocketError::OpenSSLNotAvailable

Right now we have no other option than look at error message, which is not very reliable solution, rather having specific error classes will be much cleaner.

**Comment by geemus** [comment]
Definitely, I'd certainly welcome any PRs in that direction. Otherwise I'll try to get to it as time allows. Thanks for the suggestion!

**Comment by sandstrom** [comment]
@geemus How about an error named `CertificateError` (since it's hard to know if the certificate is incorrect, or the trusted certs store is lacking)?

Basically what the conditional does already, but with a separate error class.

Also, would you prefer that it inherits from `SocketError`, to avoid breaking backwards compatibility?

Other thoughts?

**Comment by geemus** [comment]
@sandstrom Yeah, `CertificateError` sounds good to me. I think the conditional is probably fine, it would just be a refinement to the error class raised for clarity and potentially better/nicer error handling. Probably best to still inherit from SocketError for backwards-compatibility. Arguably also it is a socket level error from excons perspective, but it does seem slightly weird. Make sense? Thoughts?

**Comment by geemus** [comment]
I think, at least in terms of the certificate error, we are in a better place now.
