### ISSUE TITLE
NoMethodError from `socket.readline.chomp!.empty?` in `#parse_headers`

### ISSUE THREAD

**Issue by ryansch** [excon/excon#526]
I'm seeing this on excon 0.45.4.

response.rb `#parse_headers`:
```ruby
until (data = socket.readline.chomp!).empty?
```

It looks like `socket.readline` is returning an empty string which `chomp!` is turning into `nil`.  This raises a NoMethodError which gets wrapped with `Excon::Errors::SocketError` on the way up.

**Comment by geemus** [comment]
Hmm. I think readline is expected to always return a string, so I'm uncertain how/why we'd be hitting this. Could you share the stacktrace? Thanks!

**Comment by ryansch** [comment]
```
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/response.rb:163 :in `parse_headers`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/response.rb:75 :in `parse`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:6 :in `response_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:372 :in `response`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:236 :in `request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:256 :in `rescue in request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:204 :in `request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:256 :in `rescue in request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:204 :in `request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10 :in `error_call`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:256 :in `rescue in request`
[GEM_ROOT]/gems/excon-0.45.4/lib/excon/connection.rb:204 :in `request`
```

**Comment by geemus** [comment]
Thanks, and the resulting error is just `no #chomp! for nil`?

**Comment by geemus** [comment]
Or `no #empty? for nil`?

**Comment by ryansch** [comment]
Ultimate error: `Faraday::ConnectionFailed: undefined method `empty?' for nil:NilClass (NoMethodError)`

**Comment by geemus** [comment]
Got it. I think it should just be chomp without the bang. I'll make a quick patch.

**Comment by ryansch** [comment]
Thanks!

**Comment by geemus** [comment]
I just pushed a (likely) fix. I'm surprised this hasn't come up before. I suspect the server you are interacting with might be (slightly) misbehaved. I think chomp! there should usually work, the readline grabs everything until `\n`, but that should usually leave `\r` behind for the `chomp!` to remove (therefore not leaving a nil). As such I had just used the modify-in-place version previously as it should be much more memory efficient.

Anyway, maybe give that a shot and see if you have better luck? Thanks!

**Comment by ryansch** [comment]
Interesting.  This is in 'conversation' with an elasticsearch cluster.

I was surprised to find that `chomp!` and `chomp` have different return values.

**Comment by ryansch** [comment]
I have the fix deployed.  We were only seeing this exception about once every 3 days.  If I don't see anything in a week I'll consider it fixed.  :smile:

**Comment by geemus** [comment]
Great, just let me know. Assuming it is good I'd be happy to cut a release.

Yeah, the two chomps vary just subtley.

If something is removed you get back the string without that in both cases (and the bang case also modifies the string, whereas without bang it returns a brand new string with the contents of the old one without the removed stuff).

If, however, nothing is removed, things get more surprising. In this case, the non-bang version works the same (it returns a copy of the string with nothing removed and does not modify the original). The bang version also does not modify the original, but in this case returns nil (so that you have some way of knowing whether a modification occurred or not, as just inspecting the potentially modified string doesn't help).

Hope that clarifies, it is a weird edge case that most people don't run into. As I mentioned here, since it is in the core part of excon workflow, I had opted for the more dangerous bang version because I didn't think nil would ever be hit and I didn't necessarily want to have to create all the extra objects in memory (one per header for every request). Granted ruby should garbage collect them away without too much trouble, but it just seemed better to skip over that part if it ought to work.

All that said, I'm uncertain why you would just occasionally be seeing this as you describe. Are you holding the connections open for extended periods or just for individual requests? It may be that it just happens around server restarts or something like that (which would presumably be fairly infrequent and somewhat happenstance if a particular request happened during it or not).

**Comment by ryansch** [comment]
We're holding the connections open with: https://github.com/aceofsales/faraday_persistent_excon

We only switched away from `net-http-persistent` about a week ago.

**Comment by geemus** [comment]
I hadn't seen that before, neat stuff!

Yeah, the reason I asked was a suspicion that it might happen relating to the server closing the connection (ie around idle timeout). Might just be a matter of clock drift or something also that it thinks the timeout has been reached a little bit more quickly/slowly than the other machine believes. Anyway, hopefully this will make it not be an issue and/or make it easier to resolve for you.

**Comment by ryansch** [comment]
Thanks!  I wrote it because it didn't seem like anyone was doing persistent connections with excon and faraday.  I look at all of the other http options (typhoeus, patron, etc) and they all have threading issues of some kind.  We're running all of our elasticsearch and salesforce connections through it in production now.  At some point I hope to spend some time on getting a real test suite going (bench testing only goes so far...).

**Comment by geemus** [comment]
Cool, yeah. Persistent connections were one of the core values I had when I started with excon, unfortunately I found that many, if not most, servers tended to have short enough timeouts and/or unpredictable enough behavior around long connections that it was hard to make any general case assumptions. That said, great to hear it has been useful in this context. Historically there has even been some discussion around excon having built in (or easily available) connection pool stuff, but it never really went anywhere so far. As this matures perhaps it will be something we can revisit in terms of bringing it in house as a native capability.

**Comment by ryansch** [comment]
That would be fantastic!  I'd love for it to be as useful to people as possible.

**Comment by ryansch** [comment]
You can see in the following graph of our elasticsearch connections where we switched over:

<img width="835" alt="screenshot 2015-08-28 11 34 36" src="https://cloud.githubusercontent.com/assets/146013/9554171/cf2a22be-4d78-11e5-9a2e-cf8c1acb2b0c.png">

**Comment by geemus** [comment]
Very nice! Would definitely be up for discussing about how we could make this a native feature. The demand has been there, but I lacked the confidence (from not having personal experience) of putting it all together.

**Comment by geemus** [comment]
See also (for previous discussion): https://github.com/excon/excon/issues/330

**Comment by ryansch** [comment]
I haven't forgotten about this but it'll be a medium term sort of project.

**Comment by geemus** [comment]
@ryansch cool, thanks for the update. Let me know if there is anything I can do to help.
