### ISSUE TITLE
Streaming requests shouldn't be idempotent

### ISSUE THREAD

**Issue by wangteji** [excon/excon#530]
When making streaming requests using a response_block, it is possible for the block to process several chunks of data successfully before encountering an error. When the idempotent option is set to true, Excon will silently retry the entire request from the beginning and that can cause a host of problems. 

Here is an actual example demonstrating this behavior:
```ruby
require "excon"
expected_bytes = nil
chunks = []
repeats = 0
streamer = lambda do |chunk, remaining_bytes, total_bytes|
  expected_bytes ||= total_bytes
  chunks << chunk
  if repeats < 1
    repeats += 1
    raise Excon::Errors::Timeout, "Boom"
  end
end
Excon.get("https://twemproxy.googlecode.com/files/nutcracker-0.3.0.tar.gz", :response_block => streamer, :idempotent => true)
downloaded_bytes = chunks.inject(0){ |sum, chunk| sum += chunk.length }
downloaded_bytes == expected_bytes # => false
downloaded_bytes # => 2873682
expected_bytes # => 1825106
chunks[0] == chunks[1] # => true
(chunks[1].length + chunks[2].length) == expected_bytes # => true
```

In the above scenario, we can see that we downloaded more bytes than expected since Excon repeated the request from the beginning after the Timeout error occurred. We can also see that no error was raised and there was no indication, other than the remaining_bytes block argument, that anything was potentially wrong.  You could argue that developers could simply set idempotent to false when streaming, but that is not always possible, especially when working with other gems that use Excon under the hood. Fog, for instance, hardcodes idempontent to true for certain requests, including those with the potential to use streaming (see https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/get_object.rb#L55).

**Comment by geemus** [comment]
This is tricky, certainly. I agree that not having more info available than chunk/remaining/total makes it difficult to know if a retry has occurred or not. That said, my inclination is to make it do what you ask (rather than turning idempotent off, even when set to true, in this circumstance). Some users may be able or willing to have the chunking check for retries and do whatever might be needed. I think we could certainly improve the interface, but I fear simply turning off idempotent here would be unexpected (and there wouldn't be a clear way for someone to force idempotent if they truly wanted it).

That said, libraries utilizing excon are a different matter. fog should probably either do something to make the retries transparent or disable idempotent for these calls, as you suggest. Happy to discuss further, but I suspect most further discussion will be over there instead (please let me know if you disagree). Thanks!

**Comment by wangteji** [comment]
That makes sense to me. I definitely agree that it would be unexpected for Excon to silently disregard the idempotent option for streaming requests when it was explicitly set to true. Perhaps in the future we can add something to the interface to make the retries more transparent.

**Comment by geemus** [comment]
Yeah, definitely. I'm not sure off hand what that would look like, but if it is common enough we could certainly work through it and try some stuff. For now it seems like we know what to do for this particular case though. Thanks!
