### ISSUE TITLE
Headers are read one byte at a time

### ISSUE THREAD

**Issue by colinmarc** [excon/excon#565]
I started an http server on ubuntu 12.04 with `python -m SimpleHTTPServer 8080` and then strace'd this test script:

```
require 'excon'

loop do
  puts "press enter to continue"
  gets
  Excon.get("http://localhost:8080/foo.txt")
end
```

Excon seems to be calling `read` for one byte at a time:

```
read(7, "H", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "T", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "T", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "P", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "/", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "1", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, ".", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "0", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, " ", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "2", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "0", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "0", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, " ", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "O", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "K", 1)                         = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "\r", 1)                        = 1
fcntl(7, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
read(7, "\n", 1)                        = 1
```

I'll dig into the code and see if I can figure out a fix, but figured I should open an issue first. =)

**Comment by geemus** [comment]
As they are nonblocking writes, it will return as soon as possible. So it may have to do with the way the server is responding, more than what excon is doing (I would expect it to actually try to get as much as 1MB as a time by default, but due to non-blocking nature it will settle for whatever it can get).

**Comment by colinmarc** [comment]
It looks to me like it's explicitly reading one byte at a time for the headers: https://github.com/excon/excon/blob/master/lib/excon/socket.rb#L45

**Comment by colinmarc** [comment]
I confirmed that in my test case, it's eventually reading the whole body in one go. Still seems a bit weird, since I think simple buffering would fix this? But obviously a lot less important if it's just the headers.

**Comment by geemus** [comment]
Ah, yeah. I forgot about this part. The headers are a weirder/more complicated case as you don't have any info about how much there is (or isn't). Still seems like we could do better than this, but as you mention, since it is just the headers, the impact isn't as bad as it would otherwise be. Still, may be time to revisit this as I think it snuck in amidst relatively unrelated changes (if I'm remembering accurately from what history/blame shows me).
