### ISSUE TITLE
Overall request level timeout

### ISSUE THREAD

**Issue by colin-jack** [excon/excon#596]
There does not seem to be a way to apply an overall timeout to a request.

I have looked at connect_timeout, read_timeout, and write_timeout but what I really want is an overall timeout. Timeout::timeout seemed one option but appears to have is own issues which I would prefer to avoid

**Comment by geemus** [comment]
`Timeout::timeout` does in fact have it's own issues. Unfortunately we don't currently have an overall timeout setup, as the book-keeping gets a little hairy. In most cases we have found ways to make the existing timeouts work well enough. Could you detail your situation a bit more so that I can understand where you are having trouble? Thanks!

**Comment by mahemoff** [comment]
I believe `read_timeout`refers to idle time rather than total time. For example, pointing to a streaming URL will never terminate:

```
Excon.new('http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p', connect_time: 5, read_timeout: 5).get
```

The read timeout seems to say "raise an exception if we don't receive anything for 5 seconds" rather than "raise an exception if we are still reading after 5 seconds".

I'd like a way to guarantee this will take no more than 10 seconds. In my case, I would just want an option like `total_read_timeout`.

**Comment by colin-jack** [comment]
Hi,

Yup that's what we need too. Ideally though we would actually have a total_request_timeout which covers connecting, writing any request body, then reading response.

Thanks,

Colin

**Comment by colin-jack** [comment]
@geemus

Thanks for replying. 

On situation, we are calling what is essentially a third party http API and to provide decent user experience we would like to provide timeouts in each request. These timeouts are from a user's perspective so really we would like them to cover the entire request.

**Comment by geemus** [comment]
Understood. It seems like a reasonable thing to have, but I'm afraid that I'm unlikely to have time to work toward it in the near term. I worry a little bit about how messy it will be to support also, but regardless I would be happy to support the effort if somebody would like to give it a try. Thanks!

**Comment by mahemoff** [comment]
Not sure if I'll have time in the short term either, but looks like the main logic [is here](https://github.com/excon/excon/blob/789218e4786f90ebc3201b89d7b00000aee9e411/lib/excon/socket.rb#L256):

```
  def select_with_timeout(socket, type)
      select = case type
      when :connect_read
        IO.select([socket], nil, nil, @data[:connect_timeout])
      when :connect_write
        IO.select(nil, [socket], nil, @data[:connect_timeout])
      when :read
        IO.select([socket], nil, nil, @data[:read_timeout])
      when :write
        IO.select(nil, [socket], nil, @data[:write_timeout])
      end
      select || raise(Excon::Errors::Timeout.new("#{type} timeout reached"))
  end
```

The Connection class would need to track start time and the above could then be updated to  something like:

```
  # in Connection class
  overall_time_remaining = overall_timeout - time_so_far

  # in Socket#select_with_timeout
  when :connect_read
    `IO.select([socket], nil, nil, [@data[:connect_timeout], @data[:overall_time_remaining]].min)`
  …
```

**Comment by geemus** [comment]
Yeah, having it pull the min of connect and remaining sounds reasonable. I'd add that maybe we want to change it to do a compact and then min, as overall is probably optional? I think otherwise this sounds likely to be along the right track (for reads), if it is for the overall request we probably need to do this on the write side as well?

**Comment by mahemoff** [comment]
Agreed on compact to make the "overall" param optional and also agree it should apply to all commands, ie writes too.

**Comment by misalcedo** [comment]
👋 Hello,
I decided to try implementing this. Here is my PR adding a total timeout to non-blocking sockets. The PR description has some more details.

https://github.com/excon/excon/pull/835

**Comment by geemus** [comment]
@misalcedo Thanks! Today was a bit hectic so I didn't get to it, but I hope to give some feedback in the next 2-3 days.

**Comment by misalcedo** [comment]
@geemus Thanks for the reviews. Is there anything for me to do to get this included in a release? Also, if the request timeout test is still flaky feel free to mention me and I'll take a look. I'll try to keep an eye out for it just to be safe.

**Comment by geemus** [comment]
@misalcedo sounds good. I don't think anything else should be needed for release. That being said, I'm busy this week celebrating US Thanksgiving holiday with family, so I'm planning on waiting until at least early next week when I'm a bit more available and attentive to do the next release.
