### ISSUE TITLE
Remove support for ENV variable configuration

### ISSUE THREAD

**Issue by JanStevens** [excon/excon#605]
I wasted a day figuring out why a request with excon was not working just to finally find out some application sets `HTTP_PROXY` (for a perfect valid reason). Since excon is such a popular library and used in alot of API clients this means this global option sets it for ALL THE CLIENTS IN ALL APPLICATIONS FOR THE SAME USER not good.

Setting ENV variables and then configuring excon on a global level is really a bad idea.
People most of the time don't have much control over their env variables let alone have a clue what they contain. Especially on servers.

Excon can be configured using a proxy when initializing this should be good enough. If somebody needs support for proxy in some sort of client they can make a pull request and add proxy support in a sane way.

Also since `NO_PROXY` is included but not document this makes it even more confusing. I personally didn't manage to get it working (should the full URL, match only the host with or without schema??).

I proposed two possible solutions:
- Remove any configuration done through ENV variables, people should use `Excon.new(.... proxy: {})`
- Prefix ENV configuration variables with `EXCON` so people that still want to use ENV variables for configuration can set `EXCON_HTTP_PROXY`

Regards and thanks for the awesome lib!

**Comment by geemus** [comment]
I agree this can be confusing and surprising, but we had reasonable reasons (so I'm reticent to totally remove it). Since it is a low level library, a lot of other things use it, so without something like this you don't always have any way to set things at all. Additionally, a number of other clients use and respect these values, so we were trying to follow that precedent (ie things like curl).

We should definitely document `NO_PROXY`.

As I stated above, I'm more reticent to make the backwards-incompatible change to different ENV (or no ENV). It seems like there are a number of valid use cases for it, but I also agree that it can lead to inadvertent cases which can be confusing. I think the ENV values are only used if an explicit value is not specified, so there are ways to override them. It does seem like we should think about ways to make it clearer when these values are used, especially around errors. I think these values appear when using `EXCON_DEBUG` for instance, but I don't think they are necessarily called out specifically and clearly as coming from ENV. I certainly welcome discussion around how we can improve, thanks!
