### ISSUE TITLE
IO::EINPROGRESSWaitWritable:  Operation now in progress - connect(2) would block

### ISSUE THREAD

**Issue by david-dumas** [excon/excon#623]
Using gems kong 0.2.0 + excon 0.49.0 to connect to kong in our parallel rspec test suite. We issue multiple connections from a GitLab build container.

Kong has been running in a container with ip 172.17.0.6 on ports 5300/5301 for a month or so. I don't understand why sometimes we get this error:

```
     Excon::Errors::SocketError:
       No route to host - connect(2) for 172.17.0.36:5301 (Errno::EHOSTUNREACH)
     # ./app/models/sodata/concerns/kong_concern.rb:43:in `create_consumer'
     # ./app/workers/editor/kong_consumer_worker.rb:9:in `perform'
     # ./app/models/sodata/concerns/kong_concern.rb:27:in `create_consumer_async'
     # ./spec/support/helpers/authentification_helper.rb:3:in `authenticate'
     # ./spec/features/overridings/overridings_campaign_status_spec.rb:13:in `visit_template_campaigns_list'
     # ./spec/features/overridings/overridings_campaign_status_spec.rb:112:in `try_override_change'
     # ./spec/features/overridings/overridings_campaign_status_spec.rb:138:in `block (5 levels) in <top (required)>'
     # ./spec/support/sidekiq.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/support/sidekiq.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:14:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # IO::EINPROGRESSWaitWritable:
     #   Operation now in progress - connect(2) would block
     #   ./app/models/sodata/concerns/kong_concern.rb:43:in `create_consumer'
```

Everything usually works fine, this error show up now and then.

**Comment by geemus** [comment]
Strange. I believe the wait-writable should retry, up to a timeout. Maybe the timeout is occasionally being reached?

**Comment by perlun** [comment]
FWIW, I'm seeing similar behavior when trying to use VCR + excon in my unit tests. The stack trace is somewhat different though. The URL being requested is a http://localhost:8000 URL.

```
    NoMethodError
       undefined method `to_hash' for nil:NilClass
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/structs.rb:497:in `to_hash'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `block in interactions_to_record'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `map'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `interactions_to_record'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:118:in `serializable_hash'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:263:in `write_recorded_interactions_to_disk'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:65:in `eject'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr.rb:156:in `eject_cassette'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr.rb:191:in `ensure in use_cassette'
     # /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/vcr-3.0.3/lib/vcr.rb:191:in `use_cassette'
     # ./spec/integration/api/lso/apps_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # IO::EINPROGRESSWaitWritable:
     #   Operation now in progress - connect(2) would block
     #   /Users/plundberg/.rvm/gems/ruby-2.5.1/gems/excon-0.62.0/lib/excon/socket.rb:126:in `block in connect'
```

**Comment by geemus** [comment]
Thanks, somehow I totally missed it in the first report (maybe because there wasn't a clear line reference in the stack trace), is that this is an error during connect (not during write, where this is handled). Shouldn't be too hard of a fix, will try to get to it soon.

**Comment by geemus** [comment]
@perlun it sounds like you have an easy to execute reproduction (which I'm sorely lacking). I think the PR linked above should fix it, but it would give me more confidence if you could confirm it fixes your error. I'd love to add something to the test suite to confirm, but I'm not really sure how to cause this issue. Thanks!

**Comment by perlun** [comment]
@geemus Thanks for the attempted fix. I _thought_ I had a way to reproduce this, but now that I try (by switching over my use of VCR to use `excon` instead of `net-http` and also changing the tested code to call the Excon API instead of Net::HTTP)... I _do not_ get this error. 😞  Neither with the latest released excon version, nor with the version from your branch (I tested both.)

What my use case looks like:

- An RSpec test case that tests a Rack app (using [rack-test](https://rubygems.org/gems/rack-test))
- I use [vcr](https://rubygems.org/gems/vcr/versions/3.0.3) to mock the requests being made _from this Rack app_.
- The Rack app makes requests using Excon to a series of ports (http://localhost:8000 through http://localhost:8099), scanning to see which ones are active or not.

That was the _specific_ thing that triggered this. Maybe this can help you formulate something for the test suite (or even yet, be able to reproduce the issue with the published version of the gem.)

**Comment by geemus** [comment]
@perlun well, I'm glad you aren't having the issue any more at least. It's probably intermittent, rather than a consistent error (that is what I've seen with the related nonblocking errors). I'll bring it in anyway, as it shouldn't hurt anything. Hopefully it will prevent recurrence, even if it is difficult for us to prove at present.
