### ISSUE TITLE
Intermittent SSL handshake failure when communicating with AWS SQS.

### ISSUE THREAD

**Issue by lockstone** [excon/excon#637]
We're seeing the following SSL Error when attempting to call Fog AWS SQS delete_message: "SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)"

Below is the stack trace we get. I did just update to Excon 0.57.1, but based on the change log, that's not going to make any difference.

Not sure if this is something that can fixed in Excon, but wanted to point it out. I'm thinking of adding some code to swallow this particular error and do some retries. But I'm not a fan of doing that unless there aren't any options to actually fix the underlying issue.
```
ruby/2.4.0/gems/excon-0.57.0/lib/excon/ssl_socket.rb:117:in `connect_nonblock'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/ssl_socket.rb:117:in `initialize'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/connection.rb:403:in `new'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/connection.rb:403:in `socket'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/connection.rb:100:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/mock.rb:48:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/middlewares/base.rb:16:in `request_call'
ruby/2.4.0/gems/excon-0.57.0/lib/excon/connection.rb:249:in `request'
ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/sax_parser_connection.rb:35:in `request'
ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:7:in `request'
ruby/2.4.0/gems/fog-aws-1.3.0/lib/fog/aws/sqs.rb:155:in `_request'
ruby/2.4.0/gems/fog-aws-1.3.0/lib/fog/aws/sqs.rb:140:in `request'
ruby/2.4.0/gems/fog-aws-1.3.0/lib/fog/aws/requests/sqs/delete_message.rb:18:in `delete_message'
```

**Comment by geemus** [comment]
Hmm. It may be as simple as setting the `idempotent` parameter for that request. We use that for a lot of other requests where we would rather just retry (since it would be fine to try and delete a deleted thing again, presumably). It doesn't really look like SQS is using the flag yet, but there are plenty of other examples throughout AWS usage. All that said, I'm not certain idempotent would catch this particular error, but it won't hurt anything either. What do you think?

**Comment by lockstone** [comment]
I think SQS is using the idempotent flag, no?

https://github.com/fog/fog-aws/blob/master/lib/fog/aws/sqs.rb#L117

In my admittedly brief reading, once it gets to Excon, it looks like the default retry_limit is 4, and there's no default retry_interval, and neither retry_limit nor retry_interval get passed to Excon from the Fog SQS class.

So if I did pass the idempotent flag, it looks like it would retry 4 times in rapid succession, which seems unlikely to work. So maybe wrapping it myself and doing some retries with an exponential backoff might be the way to go?

**Comment by geemus** [comment]
@lockstone I believe the part you mention will set idempotent, but only if the params passed in contain it (which in this case, I don't believe they do). The retries are normally in rapid succession, with reconnect attempts if needed (I think?). You may ultimately need to wrap it to get what you want, but idempotent seems easier/faster and might "just work". Also with the new retry_interval stuff in excon, you may be able to use that instead of needing to custom write something (though that is very new and not yet released if I recall, let me know if you need that release cut). Does that make sense?

**Comment by lockstone** [comment]
Hi Wesley, just wanted to let you know that I implemented a retry around the fog call itself and that's resolved the issue. It seems AWS, at least their SQS service, has issues around SSL connections that result in these errors happening fairly frequently. Oddly, our other AWS calls via Fog don't seem to have this problem.

In any event, you can close this issue out if you like.

**Comment by geemus** [comment]
@lockstone yeah, some of the other AWS stuff already uses idempotent, which may help. And it does seem to vary somewhat from service to service. In any event, glad to hear you got everything worked out satisfactorily.
