### ISSUE TITLE
Use Relative Paths?

### ISSUE THREAD

**Issue by mltsy** [excon/excon#638]
It would be great if when I defined a new connection with `Excon.new("http://hostname/api/path/", ...)` I could append endpoints to that api path using the `path` option.  It seems like that's not possible currently, so I find myself creating helper methods or repeating the same `api/path` over and over.

Am I just missing something?  Or is that a feature we could add? (Maybe using a separate option like `relative_path` to avoid breaking current usage)

**Comment by geemus** [comment]
I believe you are correct, if you specify something with a path in `new` and don't pass a path param later, it will use that path. But if you pass a path param later, it will fully replace the existing value from the original URI.

I gather from your description that the first part of the path must always be the same in this usage? I'm not sure how `relative_path` would work exactly, but I'd be happy to hear more. Otherwise, a simpler option might be something like `path_prefix` which would simply prepend (I suggest this because I think it might be less complex than I at least imagine relative_path might be).

What do you think?

**Comment by mltsy** [comment]
Yeah, that's right.  For a lot of APIs for instance, the first part of the path is always the same (usually something like `/api/v2`).  My thought for `relative_path` was just that instead of deleting the path included in the original URI, it would append to it.  (I was actually surprised that wasn't the default behavior - I wonder if or how many people rely on the current "replacement" behavior... ?)

`path_prefix` would be a fine solution - the only concern I have is that it would be a little confusing to combine an original URI that has a path in it with the path_prefix option... I'd assume the path prefix wouldn't apply to that URI, but would apply to any path you pass in, which feels a little inconsistent.  I still kind of prefer the `relative_path` option, just for that reason (or maybe changing the default behavior, unless people rely on and would complain about that) :)

**Comment by geemus** [comment]
How much people rely on the current behavior is a good question, but unfortunately not one we can easily answer. I would shy away from changing it though, as replacement is how everything else works (ie headers, host, etc). The idea being you can set global defaults, override them at the connection level and override them at the request level, such that the most specific one "wins" in each case. I think it is probably worth maintaining that expectation for all parameters, rather than making path an exception.

You make a good point about there being some potential confusion around `path_prefix` though. I think it would be fine in cases where you explicitly specify `host` and `path` separately, but in the case where path get's parsed out from a full url, it seems like it would be pretty surprising to find the actual path used didn't necessarily match what you seemed to have passed in explicitly. Then again, if you are passing `path_prefix` it is hopefully for a reason and you could just make a point of passing `path` distinctly for clarity. And/or it could error/warn if you pass both a URL with path and a path_prefix (though that seems heavy handed). I guess I would lean toward having it "just work" at first and revisiting with warning/error only if it was confusing people. Besides, as a net-new feature, we have some freedom to decide how it all works (vs changing existing behavior that may or may not be relied upon, which comes with it's own dangers).

Does that make sense? What do you think?

**Comment by mltsy** [comment]
Ooh, I see your point now, regarding all the options being overridable.  I think you're right that really the primary confusion comes from that "path" option being parsed out from the URI, if it includes a path.  I didn't actually realize that's what was happening until you mentioned it now, at which point it made perfect sense ;)

I light of that, I would actually lean toward raising an exception if you set a `path_prefix` and also set a URI that includes a path.  There's no good reason I can think of that you should be using both together right? That would only serve to confuse the next guy to look at your code, if you have a URI that actually isn't a valid URI (because it has to have a prefix injected into the middle of it to be valid).  If we can do that, I like the `path_prefix` solution :smile: 

And then in the future there's still the option to change the default behavior so that any path included in the URI would be parsed as a `path_prefix` instead of a `path`.  Which seems more intuitive and useful to me.  You could still override it per request with `path_prefix`, but if you just set a `path` on a specific request then it would append to the path in the original URI (which makes more sense than setting up a resource-specific path in your connection, and then overriding it with a different resource-specific path on each request).

**Comment by geemus** [comment]
Yeah, this explains in brief the options merging stuff: https://github.com/excon/excon#options (I'd welcome feedback on how to make it clearer or more prominent).

Erroring in the case of having both does seem least surprising, so I could get behind that.

I have mixed feelings about what the eventual default should be. I certainly understand what you mean about intuition, but peoples intuition varies (and I fear it might break a lot of stuff at first). It's something I'll continue to ponder though.

To hopefully clarify and reiterate:
1. `:path_prefix` + `:path` will result in the final path used. I would suggest for simplicity that we just join them directly (rather than trying to be fancy and conditionally add in slashes or anything else). That should hopefully be the easiest to explain and understand.
2. `:path_prefix` should be something you can set in defaults, on the connection, and/or on the request and it should use the most specific one as the final value (similar to other options).
3. In cases where a path is parsed from `:uri` and `:path_prefix` is also set, we would raise an error.

Does that align with your understanding? Would you be interested in working on a PR for it? Thanks!

**Comment by yumitsu** [comment]
Why not just add a `:relative` param? And use it like `client.get(:path => '/somepath', :relative => true)`. If `:relative` is true, then `:path => '/somepath'` doesn't overrides `:path`, but instead concatenates with `:path` set up by `Excon.new`.

**Comment by mltsy** [comment]
Hmm.... that could work, but I don't love the idea of having to pass `relative: true` on every request.  It also makes the logic for merging the options a little more complex.  I do like the last outline @geemus gave overall.

I mean... I still don't see a good use case for the original URI being parsed into an overridable `path` as opposed to `path_prefix` :wink: But that's how it is currently, so I'm sure someone's using it that way.  If we made this a major version update though (to break that behavior, now or later), all they'd have to do to get the original behavior is split the URI into `host` and `path` options when creating the connection.

I haven't been implementing any Excon stuff recently, so haven't been able to justify getting back to this to try putting in a PR unfortunately.  But I think the plan sounds good!

**Comment by geemus** [comment]
The one use case where it is kind of nice:

`Excon.get('https://example.com/path')`

or (though it seems like a more of a stretch):

`Excon.new('https://example.com/path').get`

I'm not sure how often those really come up in actual usage though (and using new connections all the time isn't really best practice besides). That being said, I think it's more about the general expectations. Everything else is a straight override, not a merge. So having this be a merge seems surprising (to me). I grant that @mltsy and I disagree on which way seems surprising though.

**Comment by mltsy** [comment]
Oh, I don't think those use cases are a stretch at all!  I can definitely see the usefulness there.  But both of those use cases would remain exactly the same, even if we were to start parsing the `/path` part into the new `path_prefix` option.  The resulting URL requested given your code above would be just as it is now.  The part I haven't been able to understand is, after you've created one of those connections (as above), when would you want to replace the `/path` segment with a new one ... that is, for what purpose?

If you're going to be appending various paths to the host, it makes sense to not include a path to begin with right?  The only case where I can think it might be useful to be able to replace the path you pass in to begin with is if you have an API where nearly all requests go to a single endpoint, but for some reason, a couple requests go to another endpoint, but even then it seems messy to be calling `.get` without a `path` argument most of the time, and then calling it *with* a `path` argument on those couple requests - for maintainability, you would want to either specify the path on all of the calls, or just use two separate connections for your two endpoints, right?

You're probably right that as a maintainer of this library, it's more surprising for one of the options to be a merge, whereas my perspective as a user of the library is that it just makes no sense to set and then override a path on a connection.  The good news, I think, is that if we go forward with the `path_prefix` option, then we can continue to use straight overrides, regardless of whether we choose to parse the last part of the URI into the `path` option or the `path_prefix` option! :smile:  The latter makes the most sense to me, but that *would* break/change the interface, so I would understand avoiding it for now.

**Comment by geemus** [comment]
Good point. I think I largely agree with you that the way it is now doesn't make a ton of sense, but that it is also more consistent with how everything else works (which I think makes the whole easier to understand, even if this part is weirder for it). So yeah, I think sticking with `path_prefix` is a nice middleground that can help with both. And maybe we can think more about just changing the behavior for a major release in the future (though I'm still a bit stuck on the consistency with other things issue). Thanks for continuing to talk through this with me!
