### ISSUE TITLE
[HELP] Logging requests and responses

### ISSUE THREAD

**Issue by djberg96** [excon/excon#655]
Using the `StandardInstrumentor` as a basis, I created a logging instrumentor like so:

```
module Excon
  class LocalInstrumentor
    def self.instrument(name, params = {}, &block)
      params = params.dup

      # reduce duplication/noise of output
      params.delete(:connection)
      params.delete(:stack)

      if params.has_key?(:headers) && params[:headers].has_key?('Authorization')
        params[:headers] = params[:headers].dup
        params[:headers]['Authorization'] = REDACTED
      end

      if params.has_key?(:password)
        params[:password] = REDACTED
      end

      # This would be configuration.log in azure-armrest
      logger = params.delete(:logger)

      if params[:scheme] && params[:host] && params[:path] # request
        info = params[:scheme] + "://" + File.join(params[:host], params[:path])

        if params[:query]
          info += "?" + params[:query]
        end
      else # response
        info = params[:body]
      end

      if logger
        logger.log(logger.level, name)
        logger.log(logger.level, info)
      end

      if block_given?
        yield
      end
    end
  end
end

logger = Logger.new("excon.log")

connection = Excon.new(some_url, :instrumentor => Excon::LocalInstrumentor, :logger => logger)
```

This sort of works, but it has two issues. First, it requires adding a request param that really has nothing to do with what I'm trying to collect. I'd rather not have to add that. Second, it only logs requests, but not responses.

Can you show me how to log both requests and responses using Excon without adding an artificial request parameter?

On a side note, the only logging library for Excon that I could find was https://github.com/trusche/httplog, but it's too invasive, essentially redefining methods for any of its supported libraries, which could cause havoc in a large project where I don't have control over other plugins and the libraries they use.

**Comment by geemus** [comment]
You'll want to also look carefully at the middleware that drives the instrumentor: https://github.com/excon/excon/blob/master/lib/excon/middlewares/instrumentor.rb

In particular, the first argument to the instrumentor (name), will include whether it is a request/response/error. It should look like: `"#{datum[:instrumentor_name]}.response"` (or similar, like request, retry, error). I think you should be able to switch on that to determine how to interpret a particular call to the instrumentor.

I think passing an argument to specify the logger seems reasonable enough. Especially if you can just set it in defaults or at the connection level (having to set it for every request does seem weird). That said, you may not want to delete it from the datum during the request (because then it will not be there for the response to also use).

Hope that helps, but do let me know if I can further clarify for you. Thanks!

**Comment by djberg96** [comment]
@geemus I'm just not following what I'm supposed to do here. Am I supposed to subclass the base middleware class then? How do I pass an argument? I'm not getting it.

**Comment by geemus** [comment]
Sorry that was unclear. You should be able to use your instrumentor with some small modifications. In particular, you can change it so that when `#instrument` is called, the name argument will contain a value that will tell you if the current call refers to request/response/etc. So within the middleware you should be able to parse this value and act upon the content of the datum based on which thing it is. Does that clarify?

**Comment by djberg96** [comment]
@geemus Ok, this is what I've come up with. I resorted to class instance variables since the `instrumentor` method is a singleton method. If there's a better approach, then please tell me.

```
module Excon
  class LocalInstrumentor
    def self.logger
      @logger ||= Logger.new(STDOUT)
    end

    def self.logger=(logger)
      @logger = logger
    end

    def self.instrument(name, params = {}, &block)
      params = params.dup

      # reduce duplication/noise of output
      params.delete(:connection)
      params.delete(:stack)

      if params.has_key?(:headers) && params[:headers].has_key?('Authorization')
        params[:headers] = params[:headers].dup
        params[:headers]['Authorization'] = "REDACTED"
      end

      if params.has_key?(:password)
        params[:password] = "REDACTED"
      end

      if name.include?('request')
        info = "request: " + params[:scheme] + "://" + File.join(params[:host], params[:path])

        if params[:query]
          info += "?" + params[:query]
        end
      else
        if params[:body]
          info = "response: " + params[:body]
        end
      end

      self.logger.log(logger.level, info) if info

      yield if block_given?
    end
  end
end

logger = Logger.new('some_file.log')
Excon::LocalInstrumentor.logger = logger

connection = Excon.new(auth_url, :instrumentor => Excon::LocalInstrumentor)
```

**Comment by geemus** [comment]
Seems reasonable, you may want to be further discerning in your name check though, as I think in addition to request/response, you might get error/retry. You could just check for response and then drop the other ones if you don't care about them though.

**Comment by djberg96** [comment]
@geemus Understood, thanks!
