### ISSUE TITLE
Any plans to support http 2.0?

### ISSUE THREAD

**Issue by prog1dev** [excon/excon#687]
And if none then what reasons for that?

**Comment by geemus** [comment]
I've given it a little thought, and currently don't feel like just adding it would necessarily be the best plan. I'll try to describe some thoughts:

1. HTTP/2 is much more complicated, and the overlap with HTTP/1 is somewhat small. I'm concerned that trying to build it all in here would make it harder to maintain/update/etc. I've really appreciated how focused excon has been and the simplicity that affords. So, if I were going to build a similar/compatible interface to HTTP/2, I think I would probably do it in a distinct gem to keep things nicely segregated (though perhaps it would use excon as a dependency, depending on how things worked out). This is of course more a development-time concern than one for usage, but as the primary maintainer it is one of the first things that comes to mind.
2. The excon interface doesn't currently support parallelized requests within the same connection very well (because HTTP/1 doesn't support it at all). So even if we provided a compatible interface, the benefits you could get from it would be somewhat limited by this. Perhaps that just means that a new set of interfaces would need to be added to better support parallelization, but it makes me think that the value of just letting this interface do it under the covers might be somewhat limited. This is more the user-time concern, if it isn't really that useful/interesting without parallel processing, maybe it would be more trouble than it would be worth? This is obviously much more speculative, and I'd be curious to here more about the use cases you hope to support.
3. I just had my first child, so my time/focus are a bit spoken for in the near term.

Does that help? I think those are the primary threads I've considered in relation to this so far anyway. Would certainly welcome your feedback and thoughts.
