### ISSUE TITLE
Raise an error on non-200 proxy CONNECT response

### ISSUE THREAD

**Issue by jjiang-stripe** [excon/excon#708]
When the CONNECT request fails with a non-200 response, Excon still attempts the SSL handshake which is doomed to fail. Because of this, we end up getting a misleading SSL error rather than the actual CONNECT failure. Could we raise an error [here](https://github.com/excon/excon/blob/master/lib/excon/ssl_socket.rb#L110) if the proxy connection fails? 

When I dug through the commit history, there was a [commit that used to do this, but got removed](https://github.com/excon/excon/commit/9989457cab47f5d79ddb889d8502ba614e9aeef6#diff-285943f37882150d905b5d47f5c3d47aR34).

**Comment by geemus** [comment]
Curious, not sure why I would have removed that (long enough ago I don't recall and the message is not particularly helpful).

**Comment by geemus** [comment]
In any event, I didn't see any reason not to add it back and have now done so.

**Comment by jjiang-stripe** [comment]
thank you! one small thing --  I don't think `ProxyConnectionError` is actually defined anywhere anymore so I suspect that might end up throwing a name error

**Comment by geemus** [comment]
Good catch. I don't use proxies much, and have found them difficult to write good tests around, so it's been a part of the library that is a bit less polished and more brittle I'm afraid.

**Comment by jjiang-stripe** [comment]
this'll help us a bunch with debugging, thank you again! :) when you get a chance, would you mind bumping the version so we can pick this up downstream?

**Comment by geemus** [comment]
Thanks again for the detailed report and assistance.

Released in v0.69.0.

**Comment by geemus** [comment]
There was an error in this code that was fixed in a subsequent PR, latest is now 0.69.1

**Comment by jjiang-stripe** [comment]
thanks for the heads up!

**Comment by geemus** [comment]
I also mentioned on the PR, but I definitely don't like how this (and the error in my fix) didn't get caught by the test suite. That being said, I've struggled to get a proxy analog working in the test suite to test these things and don't personally use proxies enough to test manually (even if I could do this, it would be brittle compared to automatic testing in the suite). If you have thoughts on this or advice, I would certainly welcome them. Otherwise, I fear regressions would be easy to miss.
