### ISSUE TITLE
Redefined methods in headers.rb

### ISSUE THREAD

**Issue by djberg96** [excon/excon#729]
Unless there's some trick I'm missing, there are both aliases and method definitions declared in headers.rb. Courtesy of `rubocop -l`:

```
lib/excon/headers.rb:33:5: W: Lint/DuplicateMethods: Method Excon::Headers#[]= is defined at both lib/excon/headers.rb:32 and lib/excon/headers.rb:33.
    def []=(key, value)
    ^^^^^^^
lib/excon/headers.rb:58:5: W: Lint/DuplicateMethods: Method Excon::Headers#has_key? is defined at both lib/excon/headers.rb:57 and lib/excon/headers.rb:58.
    alias_method :has_key?, :member?
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/excon/headers.rb:59:5: W: Lint/DuplicateMethods: Method Excon::Headers#has_key? is defined at both lib/excon/headers.rb:57 and lib/excon/headers.rb:59.
    def has_key?(key)
    ^^^^^^^^^^^^
```

**Comment by geemus** [comment]
Thanks for the heads up. I believe the commit above should fix it to what was actually intended (which is to alias the alternate names for the redefined methods to also use the redefinition, instead of referring to the historical implementation). Tests worked in both cases, which is not the most encouraging though. I think the aliased methods just aren't that commonly used, so it was more a "just in case" situation.
