### ISSUE TITLE
undefined method `sockaddr_un' for Socket:Class

### ISSUE THREAD

**Issue by lucywyman** [excon/excon#738]
Hey y'all! I'm a developer on an open source remote task runner called [Bolt](https://github.com/puppetlabs/bolt/). We've been wanting to use the [Ruby Docker API gem](https://github.com/swipely/docker-api) to connect to Docker containers, but found that we had trouble connecting to the Docker socket on Windows, getting the following error:
```
undefined method `sockaddr_un' for Socket:Class\nDid you mean?  sockaddr_in (NoMethodError)
```
Apologies for not providing the full backtrace, it takes a long time to setup and I will try to do that later.

I'm not sure if there's anything that can be done to be able to use the Docker API gem on Windows, but...if this is something we could configure around that'd be amazing!

**Comment by geemus** [comment]
My experience on Windows in particular is unfortunately quite out of date. `sockaddr_un` is a method for unix sockets in particular, and works on unix based systems. I'm guessing it isn't working here due to windows not having unix socket support, but I'm far from certain of that. It looks like you might be able to have some luck with the Windows Subsystem for Linux, which seeks to address things like this: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by geemus** [comment]
Just let me know if you still have questions or concerns. Thanks,
