### ISSUE TITLE
4 test failures on s390x architecture

### ISSUE THREAD

**Issue by utkarsh2102** [excon/excon#751]
Hi @geemus,

Thanks a bunch for your work on this! 🎉 

Whilst trying to upload this package to Ubuntu, with my downstream maintainer hat on, the s390x builders there reports 4 tests failing but I can't seem to  be able to reproduce them locally in a s390x VM.

Here are the logs: https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/s390x/r/ruby-excon/20210527_201109_f8a99@/log.gz 

Do you happen to have any idea what's up with them?

**Comment by geemus** [comment]
@utkarsh2102 Thanks for reaching out, I'm not totally certain, but I'll try to share my impressions at least and hopefully those will lead is in the right direction.

Most of those tests spin up a server with known configuration/behavior, so that we can then make calls and check the response to see that things did what we expect. The particular tests that are failing all appear to be pointed at `[::1]:9293`. Rather than getting the expected response, it looks like it is getting back errors from a squid cache. This would lead me to believe that the builder server in question must already be running squid and happens to be using this port. I'm a little surprised the test wouldn't fail with the server failing to start/bind if the port is in usage though. Similarly, in your local VM, I suspect you wouldn't see this behavior unless you also configured a squid cache on 9293.

You could probably confirm this by changing the port away from 9293 and trying the builder and/or stopping squid. We may also want to dig deeper to see if we can better surface server startup/binding errors if this is in fact the culprit.

Hope that helps at least give you some more things to look into.
