### ISSUE TITLE
Hash parameters not being serialized properly

### ISSUE THREAD

**Issue by vanboom** [excon/excon#756]
I have a `put` request to an API implemented like this...

```ruby
endpoint = "https://my_api/posts/1"
response = Excon.put( endpoint, query: { post: { last_read: Time.now.to_i } } )
```

The API server is a Ruby on Rails app - the controller on that side is not receiving the params properly...

```
<ActionController::Parameters {"id"=>"1", "post"=>"{:last_read=>1627235408}"} ... >
```

Notice that the hash parameters appear to be serialized to JSON.  Should Excon serialize these properly for the controller to parse into ActionController::Paremeters properly?  Thanks for a great gem - and my apologies if I am missing something obvious here.

**Comment by vanboom** [comment]
UPDATE:  giving the `:query` argument a query string works...

```ruby
response = Excon.put( endpoint, query: { post: { last_read: Time.now.to_i } }.to_query )
```

**Comment by geemus** [comment]
Thanks for the heads up, and sorry for the delay (I was on vacation last week).

Excon does do query encoding, at least for the simple cases, as you can see here: https://github.com/excon/excon/blob/7c154c11df514ce22b6e38b88436a3de01a1fd45/lib/excon/utils.rb#L72-L92

From reviewing the code you mention and the excon implementation, I think the issue is in the handling of nested query param values. Rails has some expectations about how this is done inherited, I believe, from Rack. So, if I recall properly you would end up with something like `?post[][last_read]=123456` from active_support to_query, whereas excon will give: `?post={:last_read=>123456}` (note, I manually decoded the URI stuff for clarity). The later one is basically calling to_s on the value, which gets you that weirdness.

I would agree this is probably less than ideal, but at the same time nested query params are not really part of any of the HTTP specs. Although this would ease usage with other Ruby systems that share these nested param expectations, I worry it could create problems with servers in other languages.

As such, if you need nested params in particular, I think using to_query such as you did is probably the right approach. This ensures that the non-standard format is used on both client and server side as you would expect and avoids the possibility of conflict with other languages/servers.

Does that make more sense?
