### ISSUE TITLE
Please avoid test certificates with short validity times

### ISSUE THREAD

**Issue by terceiro** [excon/excon#765]
Hi,

The test certificates used for tests have very short validity:

```
$ openssl x509 -text -in tests/data/127.0.0.1.cert.crt | grep Validity -A2
        Validity
            Not Before: Oct 27 18:42:29 2021 GMT
            Not After : Oct 27 18:42:29 2022 GMT
```

This might not be a problem for new releases. However, some GNU/Linux distributions need to keep the same version of excon for the lifetime of a stable release (typically 3-5 years), and still be able to test it (when e.g. there are stable/security updates to packages excon depend on like ruby itself for example) to check for regressions. The fact those certs expire after 1 year makes that impossible, as the tests will suddenly start failing after 1 year.

Please make those certs have very long validity periods, or (probably better), generate them at runtime when running the tests.

**Comment by geemus** [comment]
Hey, thanks for letting me know, I hadn't thought about that particular use case when setting these up.

My intuition is that it might be better to extend the duration, rather than regenerating with each test run (as this would slow down tests and might cause other issues).

I'm guessing if we bumped up/out to 10 years that should be long enough to work for stable releases generally? Do you think that would solve the problem?

The actual generation is in the Rakefile here, so it should be straightforward to change:

https://github.com/excon/excon/blob/7f62f72833a3cdcb4effd6f887dbf704bc53fa49/Rakefile#L52-L54

What do you think?

**Comment by terceiro** [comment]
sure, 10 years should work.
