### ISSUE TITLE
Excon fails to inflate specific page

### ISSUE THREAD

**Issue by xfalcox** [excon/excon#768]
Just got a bug report on discourse about an error that I tracked back to excon.

```
require 'excon'
response = Excon.get('https://bitwiggers.com/presets/d1a7c2c7-848d-425c-9058-993317cbcc9c/',
 headers: {'accept-encoding' => 'deflate, gzip'})

# fails, default in excon at 
Zlib::Inflate.new(-Zlib::MAX_WBITS).inflate(response.body)

#works
Zlib::Inflate.new(0).inflate(response.body)
```

The default inflate is set at

https://github.com/excon/excon/blob/bbb5bd791d0bb2251593b80e3bce98dbec6e8f24/lib/excon/middlewares/decompress.rb#L23

I don't know if the webserver is providing an invalid response or if excon is at fault here. Any ideas?

**Comment by geemus** [comment]
Hey, sorry for the delay, was traveling for US Thanksgiving.

One quick note, which I presume you ran into, but in case others come across this. Excon does not include deflate by default, so the code you list won't quite hit the error, it needs to be something like:

```
require 'excon'
Excon::Defaults[:middlewares] << Excon::Defaults[:middlewares] << Excon::Middleware::Decompress
response = Excon.get('https://bitwiggers.com/presets/d1a7c2c7-848d-425c-9058-993317cbcc9c/',
 headers: {'accept-encoding' => 'deflate, gzip'})
```

It looks like maybe it should be 0 as you noted to match the spec, but that servers implement this inconsistently (I was trying to refresh my memory). You can see a description of this here: https://en.wikipedia.org/wiki/HTTP_compression#Problems_preventing_the_use_of_HTTP_compression

It's been long enough that I don't recall how I ended up with that there, I suspect it may have been following the example of other libraries, but I'm pretty fuzzy on it at this point. Given the inconsistency of decompress mentioned above from different servers, and some concern about backwards compatibility, the quickest/easiest might be to only request gzip and not deflate.

I think this is probably fixable to support both in excon with some error rescue/retry, but it may be a little bit before I have more time to dig in.

FWIW, I think basically we should try to deflate with 0 (standard headers) and rescue the error that gets raised if it is raw, then retries with a negative number (-15 is currently used) to parse it raw. We should be able to test/confirm by adding another test that deflates with 0 in addition to the existing negative one. I'd certainly welcome help working on it too if anyone has the time and inclination, otherwise I'll try to find my way back to it to work through in the not too distant future.

**Comment by cameronleger** [comment]
Hello, and thank you for the reply; I totally understand the timing so there's no apology needed there. In the example, I am the owner of the Bitwiggers site, so I have an interest in getting this solved. I think your last paragraph is the direction that I would have leaned in myself as well, so I'd support it.

On my end, I have very little control over what happens. I understand that HTTP Compression is a little off, but the actual implementation comes from AWS' API Gateway, with essentially a single toggle of "enable compression." It seems to respond in a predictable way, where the _order_ of accepted encodings is considered; `gzip, deflate` would gzip, but `deflate, gzip` would deflate instead.

I also don't know exactly where the deflate is being introduced, but it's hard to fault AWS in this case because it's reasonable to expect based on the inputs. So we're left with solving it here (by repeatedly catching exceptions until settling on something that works, or completely falls through), or somewhere within the Discourse stack (by perhaps _not_ specifying deflate, and not causing this to begin with).

I'm not versed in Ruby, though if it comes to it I could probably contribute. You mentioned time constraints in the future, so I'm open to pointers on next steps.

**Comment by geemus** [comment]
That should fix it (I added failing tests first and then worked through getting everything passing again, so I feel fairly confident it should be safe, even though it changes the default). I should be able to push a release in the next few days (I generally prefer to do it doing the work week, when I'm online and checking email more often, in case anything goes wrong). Probably should be able to do this either Tuesday or Wednesday.

**Comment by geemus** [comment]
I just released the fix as part of v0.89.0. So hopefully that should solve it for you. Thanks for working through it with me.

**Comment by quimgil** [comment]
Thank you so much!

Sadly I have found another bug. The [Donate link](https://www.gittip.com/geemus/) on the Excon documentation and your personal website lead nowhere.  :)  You have already my free-as-in-beer appreciation and if you have instructions to recognize your work in a tangible way, I'll follow your instructions. :sweat smile:

**Comment by geemus** [comment]
@quimgil Glad it helped. Thanks for letting me know those are broken, I'm not sure they were ever actually used (had basically forgotten they were there). I'll try to purge them soon to remove any confusion. And I appreciate the notion, but I'm just happy to help!
