### ISSUE TITLE
bad URI(is not URI?): "https://x-access-token:****@github.com/org/repo.git/info/refs?service=git-upload-pack"

### ISSUE THREAD

**Issue by yeikel** [excon/excon#785]
Hi there, 

I am experiencing the following problem using excon `0.92.3` and ruby `2.7.0`

I tried to parse that url locally(Ruby 2.7.5) but I was unable to reproduce the problem

```
00:04:53.909  Failed to find commits: bad URI(is not URI?): "https://x-access-token:****@github.com/org/repo.git/info/refs?service=git-upload-pack"
00:04:53.909  Backtrace:
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
00:04:53.909  	/usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
00:04:53.909  	/vendor/ruby/2.7.0/gems/excon-0.92.3/lib/excon.rb:121:in `new'
00:04:53.909  	/vendor/ruby/2.7.0/gems/excon-0.92.3/lib/excon.rb:250:in `get'


Do you have any workarround for this?

**Comment by geemus** [comment]
I'm not sure, but my main guess would be that there is an `@` in the password you are redacting. If you put that in raw (not escaped) it will fail to parse it in the way you suggest. Otherwise nothing is jumping out at me as obvious culprits. Could that be the problem you are running in to? I think you can still pass it in if you separate the username and password from the URL, something like:
```ruby
Excon.get(
  'https://github.com/org/repo.git/info/refs?service=git-upload-pack',
  user: 'x-access-token',
  password: Excon::Utils.unescape_uri('****')
)
```
Does that potentially line up with what you are seeing? Short of that I'm not sure off-hand.

**Comment by yeikel** [comment]
Thank you for response. I was never able to replicate this after I reset my token. Not suere what caused it

**Comment by geemus** [comment]
@yeikel Thanks for the update. Yeah, servers and HTTP can be a bit fickle/inconsistent at times, and I've definitely had my share of issues that I never quite managed to track down. In any event, I'm glad you aren't stuck here any more.
