### ISSUE TITLE
can't stub request

### ISSUE THREAD

**Issue by Asdfif** [excon/excon#787]
I stub request `Excon.stub({url: 'http://example.com'}, {:body => 'body', :status => 200})` 
Then  i send request  `Excon.get('http://example.com', mock: true)`
And i got an error `Excon::Error::StubNotFound: no stubs matched`
Why? I can't find answer on stack over flow.
Help me please

**Comment by geemus** [comment]
@Asdfif - Great question, I think you may have identified an edge case where the matching to stubs is overly strict that we should probably fix up. When that stub is created, it parses the URL and it looks like it interprets the path as being a blank string, whereas when the call is made it defaults to a path of `'/'`. Since blank string and `/` are not the same, it doesn't match (although in this case I would argue that it really ought to.

I can work on a patch some time in the near future, but in the mean time you can also work around this problem by being explicit with the path when you create the stub (by adding a `/`). So if you stub the request this way, it appears to work as you originally expected: `Excon.stub({url: 'http://example.com/'}, {:body => 'body', :status => 200})`.

Hope that helps, let me know if you have questions and I'll update this if/when I get a chance to fix and release.

**Comment by Asdfif** [comment]
@geemus  It works. Thank you!

**Comment by Asdfif** [comment]
@geemus  but if i need to stub request like this `http://example.com/:id`. how should i do it?

**Comment by Asdfif** [comment]
i try to use Regexp`Excon.stub({url: /https?:\/\/example?.com\// }, {:body => 'body', :status => 200})` but it raise an error `URI::InvalidURIError: bad URI(is not URI?)`

**Comment by geemus** [comment]
@Asdfif great question. The stubs are setup so that if you specify a nil value, it will match anything. So that might be the easiest. So one option would be something like:

`Excon.stub({host: 'example.com', scheme: 'https', port: 443}, {body: 'body', 'status' => 200})`

By specifying host/scheme/port directly it avoids the URI parsing (which is where we ended up with the path issues before). This particular example say that anything matching that host/scheme/port should get that response (and since path is not specified, ANY path should get that response).

Conversely, you can use a regex here, but similarly I think you need to do it in the context of the parsed params (instead of the url). So in that case it might look like:

`Excon.stub({host: 'example.com', scheme: 'https', port: 443, path: /\d+/}, {body: 'body', 'status' => 200})`

That should match anything that matches the host/scheme/port and has a path containing one or more digits.

Does that answer your question?

**Comment by Asdfif** [comment]
it works, thank you <3

**Comment by geemus** [comment]
@Asdfif glad that got you what you needed. Thanks for asking and discussing.

I think I have a bug to fix for the first case (I would expect a url with no path to match there, and I think most other people would too). I can try to find some time soon, I'll have to think about how best to do it. Since there is a pretty straightforward work around, I'm also not as worried or hurried.

That and your subsequent questions make me feel like we probably have a lot of room to improve the documentation around stubs in the README as well though. I'd certainly welcome your help there. I'd love to hear if you have suggestions on how we could make that clearer and more accurate, or would love even more if you would be up for helping us with a pull request to improve the documentation.

Thanks!

**Comment by geemus** [comment]
Closed the bug in #855, going to close this as well (though docs could still use love).
