### ISSUE TITLE
Include request method in response

### ISSUE THREAD

**Issue by grobie** [excon/excon#795]
When using instrumenters to set up logging or tracing the `excon.response` notification is particular helpful as it includes the response status and request latency. The notification data already includes information about request host, port, and path among others, but notably the request method is missing.

Especially in RESTful API design it's common that different operations share the same request path. The absence of the method attribute makes it difficult to disambiguate response notifications.

Related discussion https://github.com/excon/excon/issues/757.

**Comment by geemus** [comment]
That makes sense and I could definitely see how it would be helpful to disambiguate. I think similar to what I'd said there, it was more a matter of not having thought about it (or heard about it from others) than any obvious reason to omit them. I would imagine that adding them should be a non-breaking change as well (though implementation details will matter for that to be true). I'm certainly open to this change.

Would you be interested in working on this change? We might want to talk through it a bit more just to make sure we are on the same page, but I'm hopeful it should be a fairly straightforward change to make. Otherwise I can try to get to it, but it may be a little while before I manage to do so. Thanks!

**Comment by grobie** [comment]
Thanks @geemus! If it's more than adding the necessary `method` getter/setter/hash key in the `response.rb` file I think it makes sense if you tackle it yourself. Unfortunately I don't have time to dive deep into the code base myself. Especially the part about backwards compatibility sounds like it's not quite that trivial?

**Comment by mburumaxwell** [comment]
@geemus what needs to be done here? I may have a little time to spare, even though I am not as proficient in Ruby.
At a glance, I am thinking:
1. Handle `method`, `scheme`, and `query` similar to this https://github.com/excon/excon/blob/2d1e2d9fbb6dbfd1e49e16e8aa41876220b3b318/lib/excon/response.rb#L74
2. Add methods `method`, `scheme`, and `query` similar to this https://github.com/excon/excon/blob/2d1e2d9fbb6dbfd1e49e16e8aa41876220b3b318/lib/excon/response.rb#L20-L22

Would this be acceptable?

**Comment by geemus** [comment]
@mburumaxwell Thanks for the interest in helping out. I think you are definitely on the right track and that sounds like a good approach. There are probably also some tests we would want to add to ensure it does what we expect (and to let us know should we inadvertently break it in the future), happy to talk through those as well if you have questions. Thanks!
