### ISSUE TITLE
`Excon.unstub` blows up when there are no stubs

### ISSUE THREAD

**Issue by dentarg** [excon/excon#816]
I think I would prefer it to NO-OP but maybe it should raise a nice error? 

The current error is very confusing if you don't know what's going on (the message isn't always as clear as below, showing the code that failed)

```ruby
$ ruby -rexcon -e'Excon.unstub({})'
/Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.99.0/lib/excon.rb:253:in `delete_at': no implicit conversion from nil to integer (TypeError)

      Excon.stubs.delete_at(Excon.stubs.index(stub))
                            ^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.99.0/lib/excon.rb:253:in `unstub'
	from -e:1:in `<main>'

$ ruby --disable=error_highlight -rexcon -e'Excon.unstub({})'
/Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.99.0/lib/excon.rb:253:in `delete_at': no implicit conversion from nil to integer (TypeError)
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.99.0/lib/excon.rb:253:in `unstub'
	from -e:1:in `<main>'
```

**Comment by geemus** [comment]
@dentarg Thanks for the heads up, I must have overlooked that edge case previously. I think given the way other stub related functions work that return nil on a missing stub makes sense, so that's what I went with. Does that make sense and work for you? I've also added a test for this case (expecting the nil return), so that should keep things correct moving forward.

**Comment by dentarg** [comment]
It makes sense to me. Thanks for fixing! ❤️👍🏻
